[package]
name = "cineharbor-addon-live"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cineharbor-addon-protocol = { path = "../cineharbor-addon-protocol" }
cineharbor-addon-sdk = { path = "../cineharbor-addon-sdk" }
async-trait.workspace = true
reqwest.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true