[package]
name = "cineharbor-addon-bangumi"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cineharbor-addon-protocol = { path = "../cineharbor-addon-protocol" }
cineharbor-addon-sdk = { path = "../cineharbor-addon-sdk" }
async-trait.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true